Never before I find python notebook a useful thing, so let's try it now :)

In [1]:
from digitnotdigit import DigitNotDigit
from utilities import load_notmnist
import numpy as np
import pandas as pd

Using TensorFlow backend.

## Using trained model with 5 epochs

In [2]:
# Load not-MNIST data and instantiate the classifier
notmnist_dataset, notmnist_label = load_notmnist(scaled=True)
classifier = DigitNotDigit()

In [3]:
predicted_label, digit_label = classifier.predict(notmnist_dataset)

In [4]:
# Get all the index with the label 1 (misclassified as digit)
# There are 3430 wrong labels :(
predicted_label.shape, digit_label.shape
wrong_label_idx = np.where(predicted_label == 1)
len(wrong_label_idx[0])

# Let's build "confusion matrix" for this wrong classified data
# notmnist_label (the character A- J) as the column and digit_label (0-9) as the row for this wrong labels
# Init the matrix
conf = np.zeros((10, 10), dtype=np.int)
for wrong_id in wrong_label_idx[0]:
    char_label = notmnist_label[wrong_id]
    d_label = digit_label[wrong_id]
    conf[d_label][char_label] += 1
    
# Show pretty matrix :)
conf_df = pd.DataFrame(conf, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J' ])
conf_df

     A    B    C    D    E    F    G    H    I    J
0  157   12    9  335    0    5    3   10    9    9
1    8    4    1    1    1    1    0    0  113  113
2   26    5    9    6   14   12   10    7    7    7
3    6   65  267    6   37    5  162    3   10   10
4  116   41    2    4   32   37    5  505   18   18
5    2   22   62   28   53   19   41    3    3    3
6   13   52   49   38  175  195  175    9    6    6
7    6    4    2    3    4   34    4   22    3    3
8    3  103    1    3   12    8    2    5    4    4
9    3    0    0    0    0    0    0    0    0    0

## Using trained model with 10 epochs with threshold 2500

In [15]:
# Using 10 epochs trained model
classifier2 = DigitNotDigit(model='model/cnn_mnist_10_sigmoid.h5', threshold=2500)
predicted_label2, digit_label2 = classifier2.predict(notmnist_dataset)

In [16]:
wrong_label_idx2 = np.where(predicted_label2 == 1)
print len(wrong_label_idx2[0])
conf2 = np.zeros((10, 10), dtype=np.int)
for wrong_id in wrong_label_idx2[0]:
    char_label = notmnist_label[wrong_id]
    d_label = digit_label2[wrong_id]
    conf2[d_label][char_label] += 1
    
# Show pretty matrix :)
conf_df2 = pd.DataFrame(conf2, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J' ])
conf_df2

1934

     A   B    C    D   E   F    G    H   I   J
0   60   1    2  221   0   0    2    0   2   2
1    4   2    1    0   0   1    1    0  77  77
2   15   5    2    4   7  10    1    3   0   0
3    7  98  123   14  22   6  128    3   6   6
4  107  27    0    3  17  15    1  392  10  10
5    0   8   83    3  38  10   40    1   2   2
6    3  10    3    6  43  30   31    0   0   0
7    5   1    1    3   0   9    2   10   1   1
8    4  54    1    4   6   4    2    7   3   3
9    5   0    0    0   0   0    0    0   0   0